description: >
    Implement to provide Chassis attributes.

properties:
    - name: Type
      type: string
      description: >
          The type of physical form factor of the chassis.

associations:
    - name: attached_cables
      description: >
          Objects that implement Chassis can optionally implement the
          attached_cables association to provide a link to one or more
          cables.
      reverse_names:
        - downstream_chassis
        - upstream_chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Cable
